CREATE DATABASE SENAI_HCURSOS_MANHA;

USE SENAI_HCURSOS_MANHA;

CREATE TABLE CATEGORIAS_CURSOS (
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE ALUNOS (
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(250) NOT NULL
);

CREATE TABLE PROFESSORES (
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(250) NOT NULL
);

CREATE TABLE CURSOS (
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(250) NOT NULL
	, TITULO VARCHAR(250) NOT NULL UNIQUE
	, ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS_CURSOS(ID)
	, ID_PROFESSORE INT FOREIGN KEY REFERENCES PROFESSORES(ID)
);

CREATE TABLE ALUNOS_CURSOS (
	ID_CURSO INT FOREIGN KEY REFERENCES CURSOS(ID)
	, ID_ALUNO INT FOREIGN KEY REFERENCES ALUNOS(ID)
);