INSERT INTO CATEGORIAS_CURSOS(NOME)
VALUES('Marketing');

INSERT INTO CATEGORIAS_CURSOS
VALUES('Infomática');

INSERT INTO CATEGORIAS_CURSOS
VALUES('Design'), ('Marketing');

USE SENAI_HCURSOS_MANHA

--EXERCICIOS

INSERT INTO ALUNOS VALUES('Ricardo');

INSERT INTO ALUNOS VALUES('Sallo');

INSERT INTO ALUNOS VALUES('Renato');

INSERT INTO ALUNOS VALUES('André');

INSERT INTO ALUNOS VALUES('Barbara');

INSERT INTO ALUNOS VALUES('Guilherme');