INSERT INTO PROFESSORES
VALUES('Fernando'),
	  ('Helena'),
	  ('Possarle'),
	  ('Raquel');

INSERT INTO CATEGORIAS_CURSOS 
VALUES('Gestão'),
	  ('Informárica'),
	  ('Desenvolvimento'),
	  ('Marketign'),
	  ('Design');

INSERT INTO CURSOS(NOME, TITULO, ID_CATEGORIA, ID_PROFESSORE)
VALUES			  ('SQL', 'SQL BÁSICO - PARTE 1', 14, 1),
				  ('SQL', 'SQL BÁSICO - PARTE 2', 14, 1),
				  ('JAVA', 'JAVA BÁSICO - PARTE 2', 14, 2),
				  ('REACT', 'REACT NATIVE - PARTE 1', 14, 2),
				  ('GESTÃO', 'GESTÃO DE PESSOAS', 12, 3);

SELECT * FROM PROFESSORES ORDER BY ID;

SELECT * FROM CATEGORIAS_CURSOS ORDER BY ID;

SELECT * FROM CURSOS ORDER BY ID;

SELECT * FROM ALUNOS ORDER BY ID