CREATE DATABASE SSOLVE_SERVICOS;

USE SSOLVE_SERVICOS;

CREATE TABLE CLIENTES (
	ID INT IDENTITY PRIMARY KEY
	, NOME_FANTASIA VARCHAR(250) NOT NULL
	, CNPJ CHAR(14) NOT NULL
	, RAZAO_SOCIAL VARCHAR(100)
	, ENDERECO VARCHAR(250) NOT NULL 
);

CREATE TABLE EXECUTANTES (
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(250) NOT NULL
	, MATRICULA INT UNIQUE NOT NULL
);

CREATE TABLE COMODOS (
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE TIPOS_SERVICOS (
	ID INT IDENTITY PRIMARY KEY
	, DESCRICAO TEXT
	, PRECO FLOAT NOT NULL
);

CREATE TABLE ORDEM_DE_SERVICOS (
	ID INT PRIMARY KEY IDENTITY
	, ID_TIPOS_SERVICO INT FOREIGN KEY REFERENCES TIPOS_SERVICOS(ID) 
	, ID_COMODO INT FOREIGN KEY REFERENCES COMODOS(ID)
	, ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTES(ID)
	, DATA_INICIO DATETIME NOT NULL
	, DATA_FINAL DATETIME NOT NULL
	, DESCRICAO TEXT NOT NULL
); 

CREATE TABLE SERVICOS (
	ID_ORDEM_DE_SERVICO INT FOREIGN KEY REFERENCES ORDEM_DE_SERVICOS(ID)
	, ID_EXECUTANTE INT FOREIGN KEY REFERENCES EXECUTANTES(ID)
);


