--lista os dados de uma tavela informando quais as colunas
SELECT NOME,ID, FROM CATEGORIAS_CURSOS;

--lista os dados de uma tabela filtrando/where pelo id
SELECT * FROM CATEGORIAS_CURSOS WHERE ID = 1;

SELECT * FROM CATEGORIAS_CURSOS ORDER BY ID ASC;

SELECT * FROM CATEGORIAS_CURSOS WHERE ID = 1 OR ID = 3;

SELECT * FROM CATEGORIAS_CURSOS WHERE ID = 3 AND ID = 'DESIGN';

SELECT * FROM CATEGORIAS_CURSOS WHERE NOME LIKE '%E%';

SELECT * FROM CATEGORIAS_CURSOS WHERE NOME LIKE 'I%';

SELECT * FROM CATEGORIAS_CURSOS WHERE NOME LIKE '%A';

SELECT * FROM CATEGORIAS_CURSOS WHERE ID > 1;

SELECT COUNT (*) FROM CATEGORIAS_CURSOS;

SELECT TOP 2 * FROM CATEGORIAS_CURSOS;

SELECT * FROM CATEGORIAS_CURSOS WHERE ID BETWEEN 2 AND 5;

SELECT * FROM CATEGORIAS_CURSOS WHERE NOT ID = 1;

SELECT * FROM CATEGORIAS_CURSOS WHERE ID = 1 OR ID = 3 OR ID = 6;
SELECT * FROM CATEGORIAS_CURSOS WHERE ID IN(1, 3, 6);

SELECT ID AS 'NUMERO', NOME AS 'MELANCIA' FROM CATEGORIAS_CURSOS;

UPDATE CATEGORIAS_CURSOS SET NOME = 'Desenvolvimento de Sistemas' WHERE ID = 1;

DELETE FROM CATEGORIAS_CURSOS WHERE ID = 4;

--EXERCICIOS

SELECT ID, NOME AS MEU_REGISTRO FROM ALUNOS WHERE NOME = 'Ricardo';

SELECT ID, NOME AS CONTEM_I FROM ALUNOS WHERE NOME LIKE '%I%';

SELECT ID, NOME AS COMECA_R FROM ALUNOS WHERE NOME LIKE 'R%';

SELECT ID, NOME AS TERMINA_O_OU_A FROM ALUNOS WHERE NOME LIKE '%[A, O]'

SELECT ID, NOME AS ENTRE_3_5 FROM ALUNOS WHERE ID BETWEEN 3 AND 5;

SELECT NOME AS NOME_ORDENADO FROM ALUNOS ORDER BY NOME ASC;

DELETE FROM ALUNOS WHERE NOME = 'Guilherme';

UPDATE ALUNOS SET NOME = 'Barbara' WHERE ID = 4;

