CREATE DATABASE HCursos;
GO

USE HCursos;
GO

CREATE TABLE CategoriasCursos (
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE Alunos (
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(250) NOT NULL
);

CREATE TABLE Professores (
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(250) NOT NULL
);

CREATE TABLE Cursos (
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(250) NOT NULL,
	Titulo VARCHAR(250) NOT NULL UNIQUE,
	CategoriaCursoId INT FOREIGN KEY REFERENCES CategoriasCursos(Id),
	ProfessorId INT FOREIGN KEY REFERENCES Professores(Id)
);

CREATE TABLE AlunosCursos (
	CursoId INT FOREIGN KEY REFERENCES Cursos(Id),
	AlunoId INT FOREIGN KEY REFERENCES Alunos(Id)
);

CREATE TABLE Usuarios (
	Id INT IDENTITY PRIMARY KEY,
	Email VARCHAR(250) NOT NULL UNIQUE,
	Senha VARCHAR(100) NOT NULL,
	Ativo CHAR(1)
);