CREATE DATABASE SSolveServicos;
GO

USE SSolveServicos;
GO

CREATE TABLE CLIENTES (
	ID INT IDENTITY PRIMARY KEY,
	NomeFantasia VARCHAR(250) NOT NULL,
	Cnpj CHAR(14) NOT NULL,
	RazaoSocial VARCHAR(100),
	Endereco VARCHAR(250) NOT NULL 
);

CREATE TABLE Executantes (
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(250) NOT NULL,
	Matricula INT UNIQUE NOT NULL
);

CREATE TABLE Comodos (
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE TiposServicos (
	Id INT IDENTITY PRIMARY KEY,
	Descricao TEXT,
	Preco FLOAT NOT NULL
);

CREATE TABLE OrdensDeServicos (
	Id INT PRIMARY KEY IDENTITY,
	TipoServicoId INT FOREIGN KEY REFERENCES TiposServicos(Id),
	ComodoId INT FOREIGN KEY REFERENCES Comodos(Id),
	ClienteId INT FOREIGN KEY REFERENCES Clientes(Id),
	DataInicio DATETIME NOT NULL,
	DataFinal DATETIME NOT NULL,
	Descricao TEXT NOT NULL
); 

CREATE TABLE Servicos (
	OrdemDeServicoId INT FOREIGN KEY REFERENCES OrdensDeServicos(Id),
	ExecutanteId INT FOREIGN KEY REFERENCES Executantes(Id)
);